// ============================================================
// Tests: Compiler targets
// ============================================================

import { describe, it } from 'node:test';
import { expect } from '../helpers/expect.js';
import { claudeMdTarget } from '../../src/compiler/targets/claude-md.js';
import { agentsMdTarget } from '../../src/compiler/targets/agents-md.js';
import { cursorRulesTarget } from '../../src/compiler/targets/cursor-rules.js';
import type { RulesFile } from '../../src/types/rules.js';

const mockRules: RulesFile = {
  version: 1,
  generatedAt: '2026-06-11T00:00:00Z',
  healthScore: 92,
  project: {
    name: 'test-project',
    languages: ['typescript', 'python'],
    framework: 'Next.js',
  },
  rules: [
    {
      id: 'error-handling-result',
      category: 'error-handling',
      severity: 'critical',
      priority: 95,
      description: 'Use Result<T,E> pattern for all error handling in service layer.',
      evidence: [{ file: 'src/types/result.ts', line: 1, note: 'Pattern definition' }],
      verification: { type: 'pattern-match', pattern: 'Result<', threshold: 0.9 },
      confidence: 0.95,
    },
    {
      id: 'naming-camelcase',
      category: 'naming',
      severity: 'warning',
      priority: 70,
      description: 'All function names use camelCase.',
      evidence: [],
      verification: { type: 'naming-convention', pattern: 'camelCase', threshold: 0.9 },
      confidence: 0.88,
    },
  ],
};

describe('CLAUDE.md target', () => {
  it('should generate valid markdown', () => {
    const output = claudeMdTarget.compile(mockRules);
    expect(output).toContain('Generated by auk');
    expect(output).toContain('test-project');
    expect(output).toContain('error-handling-result');
    expect(output).toContain('Result<T,E>');
  });

  it('should include critical rules section', () => {
    const output = claudeMdTarget.compile(mockRules);
    expect(output).toContain('Critical Rules');
  });

  it('should include health score', () => {
    const output = claudeMdTarget.compile(mockRules);
    expect(output).toContain('92');
  });
});

describe('AGENTS.md target', () => {
  it('should generate valid markdown', () => {
    const output = agentsMdTarget.compile(mockRules);
    expect(output).toContain('Agent Instructions');
    expect(output).toContain('test-project');
  });
});

describe('Cursor rules target', () => {
  it('should generate MDC format', () => {
    const output = cursorRulesTarget.compile(mockRules);
    expect(output).toContain('---');
    expect(output).toContain('alwaysApply: true');
    expect(output).toContain('error-handling-result');
  });
});
