// ============================================================
// auk — AI Context Engineering Platform
// Shared formatting helpers for compiler targets.
// Lives in its own module so targets don't import the engine
// (which imports the registry, which imports the targets —
// keeping this separate avoids a circular dependency).
// ============================================================

import type { Rule } from '../types/rules.js';
import type { DecisionsFile } from '../types/decisions.js';

/** Generate the header comment for compiled files */
export function generateHeader(healthScore: number): string {
  const timestamp = new Date().toISOString();
  return [
    `# Generated by auk — AI Context Engineering Platform`,
    `# https://github.com/sandeepshekhar26/develop-anything`,
    `# Generated: ${timestamp}`,
    `# Context Health: ${healthScore}%`,
    `# DO NOT EDIT MANUALLY — regenerate with: auk compile`,
    '',
  ].join('\n');
}

/** Format rules for markdown output */
export function formatRulesAsMarkdown(
  rules: Rule[],
  decisions?: DecisionsFile,
  options: { maxTokens?: number; includeEvidence?: boolean; includeDecisions?: boolean } = {}
): string {
  const { includeEvidence = true, includeDecisions = true } = options;
  const lines: string[] = [];

  // Group rules by category
  const byCategory = new Map<string, Rule[]>();
  for (const rule of rules) {
    if (!byCategory.has(rule.category)) byCategory.set(rule.category, []);
    byCategory.get(rule.category)!.push(rule);
  }

  const categoryOrder = ['architecture', 'error-handling', 'imports', 'types', 'naming', 'testing', 'file-organization', 'patterns', 'dependencies'];

  for (const category of categoryOrder) {
    const categoryRules = byCategory.get(category);
    if (!categoryRules || categoryRules.length === 0) continue;

    lines.push(`## ${formatCategoryName(category)}`);
    lines.push('');

    for (const rule of categoryRules) {
      const severityIcon = rule.severity === 'critical' ? '🔴' : rule.severity === 'warning' ? '🟡' : 'ℹ️';
      lines.push(`### ${severityIcon} ${rule.id}`);
      lines.push('');
      lines.push(rule.description.trim());
      lines.push('');

      if (includeEvidence && rule.evidence.length > 0) {
        lines.push('**Evidence:**');
        for (const ev of rule.evidence.slice(0, 3)) {
          const lineRef = ev.line ? `:${ev.line}` : '';
          lines.push(`- \`${ev.file}${lineRef}\` — ${ev.note}`);
        }
        lines.push('');
      }

      // Include decision rationale if available
      if (includeDecisions && rule.decisionRef && decisions) {
        const decision = decisions.decisions.find(d => d.id === rule.decisionRef);
        if (decision) {
          lines.push(`**Why:** ${decision.rationale.trim()}`);
          lines.push('');
        }
      }
    }
  }

  return lines.join('\n');
}

function formatCategoryName(category: string): string {
  return category
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
