// ============================================================
// auk — Compiler target: AGENTS.md
// ============================================================

import type { CompilerTarget } from '../target-registry.js';
import type { RulesFile } from '../../types/rules.js';
import type { DecisionsFile } from '../../types/decisions.js';
import { generateHeader, formatRulesAsMarkdown } from '../format.js';

export const agentsMdTarget: CompilerTarget = {
  name: 'agents-md',
  displayName: 'AGENTS.md (Universal)',
  outputPath: 'AGENTS.md',

  compile(rules: RulesFile, decisions?: DecisionsFile): string {
    const lines: string[] = [];

    lines.push(generateHeader(rules.healthScore));
    lines.push(`# Agent Instructions — ${rules.project.name}`);
    lines.push('');
    lines.push('> This file is auto-generated by [auk](https://github.com/sandeepshekhar26/develop-anything).');
    lines.push('> It contains codebase-derived rules for AI coding agents.');
    lines.push('');

    lines.push(formatRulesAsMarkdown(rules.rules, decisions, {
      includeEvidence: true,
      includeDecisions: true,
    }));

    return lines.join('\n');
  },
};
