// ============================================================
// auk — Compiler target: .aider.conf.yml
// ============================================================

import type { CompilerTarget } from '../target-registry.js';
import type { RulesFile } from '../../types/rules.js';
import type { DecisionsFile } from '../../types/decisions.js';

export const aiderConfTarget: CompilerTarget = {
  name: 'aider-conf',
  displayName: '.aider.conf.yml (Aider)',
  outputPath: '.aider.conf.yml',

  compile(rules: RulesFile, _decisions?: DecisionsFile): string {
    const lines: string[] = [];
    lines.push(`# Generated by auk — AI Context Engineering Platform`);
    lines.push(`# https://github.com/sandeepshekhar26/develop-anything`);
    lines.push('');
    lines.push('conventions:');
    for (const rule of rules.rules) {
      lines.push(`  - "${rule.description.trim().replace(/\n/g, ' ').replace(/"/g, '\\"')}"`);
    }
    lines.push('');
    lines.push(`read: [CLAUDE.md]`);
    return lines.join('\n');
  },
};
