// ============================================================
// auk — AI Context Engineering Platform
// Review reporter — generates review output
// ============================================================

import type { ReviewResult, Violation } from '../types/review.js';
import { logger } from '../utils/logger.js';

/** Print colored review report to terminal */
export function printReviewReport(result: ReviewResult): void {
  logger.header('Architectural Review');
  console.log();

  logger.keyValue('Files Changed', result.totalFilesChanged);
  logger.keyValue('Diff Base', result.diffBase);
  console.log();

  // Summary
  if (result.summary.violations > 0)
    console.log(`  ❌ ${result.summary.violations} violation(s)`);
  if (result.summary.warnings > 0)
    console.log(`  ⚠️  ${result.summary.warnings} warning(s)`);
  if (result.summary.suggestions > 0)
    console.log(`  💡 ${result.summary.suggestions} suggestion(s)`);
  if (result.summary.clean > 0)
    console.log(`  ✅ ${result.summary.clean} clean change(s)`);
  console.log();

  // Violations detail
  if (result.violations.length > 0) {
    logger.header('Details');
    for (const v of result.violations) {
      const icon = v.severity === 'violation' ? '❌' :
                   v.severity === 'warning' ? '⚠️' :
                   v.severity === 'suggestion' ? '💡' : '✅';

      console.log(`  ${icon} [${v.type}] ${v.file}`);
      console.log(`     ${v.message}`);
      if (v.explanation && v.explanation !== v.message) {
        console.log(`     ${logger.brand.dim(v.explanation.split('\n')[0])}`);
      }
      if (v.suggestion) {
        console.log(`     💡 ${v.suggestion}`);
      }
      if (v.relatedRule) {
        console.log(`     📋 Rule: ${v.relatedRule}`);
      }
      console.log();
    }
  }

  // Complexity changes
  if (result.complexityChanges.length > 0) {
    logger.header('Complexity Changes');
    for (const cc of result.complexityChanges) {
      const arrow = cc.degreeChange > 0 ? '↑' : '↓';
      const icon = cc.isGodObjectRisk ? '🔴' : '🟡';
      console.log(`  ${icon} ${cc.file}: ${cc.before.degree} → ${cc.after.degree} connections (${arrow}${Math.abs(cc.degreeChange)})`);
    }
    console.log();
  }
}

/** Generate markdown review report (for CI/PR comments) */
export function generateMarkdownReview(result: ReviewResult): string {
  const lines: string[] = [];

  lines.push(`## 🏗️ Architectural Review by auk`);
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|:--|:--|`);
  lines.push(`| ❌ Violations | ${result.summary.violations} |`);
  lines.push(`| ⚠️ Warnings | ${result.summary.warnings} |`);
  lines.push(`| 💡 Suggestions | ${result.summary.suggestions} |`);
  lines.push(`| ✅ Clean | ${result.summary.clean} |`);
  lines.push('');

  if (result.violations.length > 0) {
    lines.push('### Findings');
    lines.push('');
    for (const v of result.violations) {
      const icon = v.severity === 'violation' ? '❌' : v.severity === 'warning' ? '⚠️' : '💡';
      lines.push(`#### ${icon} ${v.type}: ${v.file}`);
      lines.push(v.message);
      if (v.suggestion) lines.push(`> 💡 ${v.suggestion}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [auk](https://github.com/sandeepshekhar26/develop-anything)*');

  return lines.join('\n');
}
