// ============================================================
// auk — AI Context Engineering Platform
// Prompt emitter — host-agent LLM enhancement, no API keys.
// auk stays deterministic; the user's agent (Claude Code, Cursor,
// Copilot…) reads .auk/prompts/*.md, writes a response JSON, and
// `auk enhance --apply` validates and merges it into rules.yaml.
// ============================================================

import * as path from 'path';
import type { Rule, RulesFile } from '../types/rules.js';
import { writeFileWithDir } from '../utils/file-utils.js';

const BATCH_SIZE = 10;

export const RESPONSE_SCHEMA_EXAMPLE = `{
  "version": 1,
  "batch": "<batch name>",
  "enhancements": [
    {
      "ruleId": "<existing rule id>",
      "description": "<rewritten description, 10-600 chars>",
      "rationale": "<optional: why this convention exists>",
      "examples": [{ "file": "<repo-relative path>", "note": "<what it shows>" }]
    }
  ]
}`;

/** Rules that still need enhancement (none yet, or core description changed) */
export function rulesNeedingEnhancement(rulesFile: RulesFile): Rule[] {
  return rulesFile.rules.filter(r => !r.enhanced || r.enhanced.stale);
}

/** Write enhancement prompt batches to .auk/prompts/; returns file paths */
export function emitPrompts(rulesFile: RulesFile, projectRoot: string): string[] {
  const pending = rulesNeedingEnhancement(rulesFile);
  const promptsDir = path.join(projectRoot, '.auk', 'prompts');
  const files: string[] = [];

  const batches: Rule[][] = [];
  for (let i = 0; i < pending.length; i += BATCH_SIZE) {
    batches.push(pending.slice(i, i + BATCH_SIZE));
  }

  batches.forEach((batch, i) => {
    const batchName = `enhance-rules-${String(i + 1).padStart(2, '0')}`;
    const outPath = path.join(promptsDir, `${batchName}.md`);
    writeFileWithDir(outPath, renderBatch(batchName, i + 1, batches.length, batch, rulesFile.project.name));
    files.push(outPath);
  });

  if (files.length > 0) {
    writeFileWithDir(path.join(promptsDir, 'README.md'), README);
  }
  return files;
}

function renderBatch(batchName: string, n: number, total: number, rules: Rule[], projectName: string): string {
  const ruleSections = rules.map(r => {
    const payload = {
      id: r.id,
      category: r.category,
      severity: r.severity,
      description: r.description,
      evidence: r.evidence.map(e => ({ file: e.file, line: e.line })),
      confidence: r.confidence,
    };
    return `## Rule: ${r.id}\n\n\`\`\`json\n${JSON.stringify(payload, null, 2)}\n\`\`\`\n`;
  }).join('\n');

  return `# auk enhancement task (batch ${n}/${total})

You are enhancing AI-context rules for the project "${projectName}".

For each rule below, rewrite the description to be clearer and more actionable
for an AI coding assistant, and add a short rationale explaining *why* the
convention likely exists. Optionally add 1-2 example references (existing
repo files only). Use the evidence files for grounding — read them if needed.

RULES:
- Do NOT change rule ids, categories, severities, or verification logic.
- Descriptions must be 10-600 characters, plain text.
- Only reference files that exist in this repository.

${ruleSections}
## How to respond

Write a JSON file matching this schema to \`.auk/prompts/${batchName}.response.json\`:

\`\`\`json
${RESPONSE_SCHEMA_EXAMPLE.replace('<batch name>', batchName)}
\`\`\`

Then run: \`auk enhance --apply .auk/prompts/${batchName}.response.json\`
`;
}

const README = `# auk enhancement prompts

These files are generated by \`auk generate --emit-prompts\` (or \`auk enhance --emit\`).

Workflow for an AI agent (Claude Code, Cursor, Copilot, …):
1. Read each \`enhance-rules-NN.md\` file.
2. Write the corresponding \`enhance-rules-NN.response.json\`.
3. Run \`auk enhance --apply <response file>\` — auk validates the JSON and
   merges it into \`.auk/rules.yaml\` without touching verification logic.
4. Run \`auk compile\` to regenerate CLAUDE.md / AGENTS.md / etc.

This directory is disposable; add it to .gitignore.
`;
